name: Codecov

on: [push]

jobs:
  report-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Codecov"
        uses: codecov/codecov-action@v2.1.0
        with:
          files: ./target/site/jacoco/jacoco.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true

