# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build, Sign and Release with Maven

# run the CI build on all PRs and branches
on: [push]

jobs:
  build-and-deploy-if-release-branch:
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout"
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        server-id: ossrh
        server-username: ${{ secrets.OSSRH_USERNAME }}
        server-password: ${{ secrets.OSSRH_PASSWORD }}
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Build with Maven
      run: ./mvnw -B package --file pom.xml

    - name: "Publish to Maven Central Repository"
      # publish to Maven Central on pushes to "release" branch
      if: github.ref == 'refs/heads/release'
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

        ./mvnw -B release:prepare release:perform -Dusername=$GITHUB_ACTOR -Dpassword=$GITHUB_TOKEN -P release
