# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Build

# run the CI build on all PRs and branches
on:
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        gpg-passphrase: GPG_PASSPHRASE

    - name:  Maven Build
      run: ./mvnw -B package --file pom.xml

    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./target/site/jacoco/jacoco.xml
        flags: unittests
        fail_ci_if_error: true
        verbose: true

    - name: Publish to Maven Repository
      # publish to Maven Central on pushes to "release" branch
      if: github.ref == 'refs/heads/release'
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

        ./mvnw -B release:prepare release:perform -Dusername=$GITHUB_ACTOR -Dpassword=$GITHUB_TOKEN -P release
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    - name: Create GitHub Release
      if: github.ref == 'refs/heads/release'
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: |
          LICENSE
          *.jar
